version: "3.8"

services:
  app: 
    build: ./your-proyect/
    container_name: app
    volumes:
      #- ./api-peru:/usr/src:rw
      - ./your-proyect:/usr/share/nginx/html:rw
    command: yarn dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    restart: always
    

  mongodb:
    container_name: app-database
    image: mongo
    volumes:
      - "./schemas/mongo:/data:rw"
    ports:
      - "27017:27017"

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro # Necesita tener este volumen para funcionar correctamente
      - ./certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy:rw

  nginx:
    image: nginx
    restart: always
    expose:
      - 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=domain.com,www.domain.com
      - LESTSENCRYPT_HOST=domain.com,www.domain.com
      - LESTSENCRYPT_EMAIL=domain.com@gmail.com